Fix opacity bug on Android (#4)
alexmngn/react-native-image-crop pull request #5
Opened 2017-01-18 14:08 UTC by lucasbento

2017-01-19 04:47 UTC, alexmngn commented
I don't have any issue running the current version on Android (Nexus 6P Emulator + API 25) and don't understand the reason of this PR. Can you explain what issue do you have? Which Android version?

See attached screenshot:

<img width="574" alt="screen shot 2017-01-19 at 11 43 16" src="https://cloud.githubusercontent.com/assets/4203845/22094006/cdf1b3e8-de3c-11e6-8fa2-ce099787bc69.png">

2017-01-26 13:10 UTC, lucasbento commented
Yes, it indeed works fine on react-native `0.31`, this is how it looks on `0.39.2` on a physical device:

![screenshot_20170126-110538](https://cloud.githubusercontent.com/assets/6207220/22332372/c2afeff6-e3b7-11e6-8699-54adf216d5ba.png)

Notice that the image parts that are supposed to have the opacity don't appear.

2017-01-30 11:02 UTC, alexmngn commented
This pull request doesn't make it looks like my screenshot anymore. You have a light background whereas I have a dark background. Can you make the change so it looks exactly the same?

2017-01-30 12:09 UTC, lucasbento commented
@alexmngn: oh, okay, since I used a white background I assumed it would be always white, gonna fix that.

2017-01-31 19:54 UTC, sibelius commented
@alexmngn @lucasbento can we get this in?

2017-02-01 03:33 UTC, alexmngn commented
@sibelius The pull request still doesn't look good to me. Waiting for @lucasbento to make the changes.

2017-02-01 12:16 UTC, lucasbento commented
@alexmngn: would it be something like this?

![screenshot_20170201-101335](https://cloud.githubusercontent.com/assets/6207220/22506436/768d1bee-e867-11e6-8a4c-6caffe3cfcdb.png)

2017-02-14 11:03 UTC, alexmngn commented
@lucasbento Yes that's supposed to be like this.

2017-02-14 16:51 UTC, lucasbento commented
@alexmngn: good, just updated it, would you mind checking it again?

2017-03-23 10:46 UTC, alexmngn requested changes

2017-03-23 10:46 UTC, alexmngn commented on index.js
> +					</Image>
Indentation not correct on this file.

2017-03-23 11:20 UTC, closed without merging

2017-03-23 11:29 UTC, sibelius commented
@alexmngn could you please fix the missing styles errors?

it has been more than 2 months to merge this simple PR

2017-03-23 11:31 UTC, sibelius commented
@alexmngn consider using prettier to avoid this in the future https://medium.com/@okonetchnikov/make-linting-great-again-f3890e1ad6b8#.d9w1oimtl

2017-03-23 11:36 UTC, alexmngn commented
@sibelius The project runs .eslintrc file and has a strict rule, you should make sure your editor is setup to accept those rules.

```
    "rules": {
        "indent": [2, "tab", {"SwitchCase": 1}],
```

I will look into it very soon and might add a few features but I don't have much time at the moment. Sorry about that.

2017-03-23 11:39 UTC, sibelius commented
> a strict rule 

how is this making us more productive?

I have no problem with spaces vs tabs, but I just would like to get our changes in the main repo to help improve the package for everybody.

but I think you are more concern with making lint work before making more features available